"""
Scheduled report generation and dispatch.

generate_report(db, target_id, since_iso, domain) → markdown string
dispatch_scheduled_reports(db) → int (reports sent)
  - Called from scheduler tick loop once per minute
  - Checks which schedules are due based on current UTC time + last_sent_at
  - Generates report + dispatches via notification_channels
  - Updates last_sent_at
"""
import logging
import uuid
from datetime import datetime, timezone

log = logging.getLogger("engine.reports")

_DOW_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


async def _is_schedule_due(row: dict) -> bool:
    """Return True if this schedule should fire now (within the current UTC hour)."""
    now = _now_utc()
    if row["hour"] != now.hour:
        return False
    if row["frequency"] == "weekly":
        if row["day_of_week"] is not None and row["day_of_week"] != now.weekday():
            return False
    last_sent = row["last_sent_at"]
    if last_sent is None:
        return True
    try:
        last = datetime.fromisoformat(last_sent)
        if last.tzinfo is None:
            last = last.replace(tzinfo=timezone.utc)
        if row["frequency"] == "daily":
            return last.date() < now.date()
        # weekly: check if last_sent is from a previous ISO week
        return last.isocalendar()[:2] < now.isocalendar()[:2]
    except Exception:
        return True


async def generate_report(
    db,
    target_id: str | None,
    since_iso: str,
    domain: str | None = None,
) -> str:
    """
    Build a markdown digest report.
    target_id=None means global across all targets.
    """
    lines = []

    if target_id:
        title = f"Recon Report — {domain or target_id}"
    else:
        title = "Recon Report — All Targets"

    lines.append(f"# {title}")
    lines.append(f"**Period:** since {since_iso[:16]} UTC")
    lines.append("")

    # ── New subdomains ─────────────────────────────────────────────────────────
    if target_id:
        sub_rows = await db.fetchall(
            "SELECT subdomain FROM subdomains WHERE target_id = ? AND first_seen >= ? ORDER BY first_seen DESC LIMIT 20",
            (target_id, since_iso),
        )
    else:
        sub_rows = await db.fetchall(
            "SELECT subdomain FROM subdomains WHERE first_seen >= ? ORDER BY first_seen DESC LIMIT 20",
            (since_iso,),
        )
    lines.append(f"## New Subdomains ({len(sub_rows)})")
    if sub_rows:
        for r in sub_rows:
            lines.append(f"- `{r['subdomain']}`")
    else:
        lines.append("_None_")
    lines.append("")

    # ── Live host changes ──────────────────────────────────────────────────────
    if target_id:
        hist_rows = await db.fetchall(
            """SELECT url, event_type, recorded_at FROM live_hosts_history
               WHERE target_id = ? AND recorded_at >= ?
               ORDER BY recorded_at DESC LIMIT 20""",
            (target_id, since_iso),
        )
    else:
        hist_rows = await db.fetchall(
            """SELECT url, event_type, recorded_at FROM live_hosts_history
               WHERE recorded_at >= ?
               ORDER BY recorded_at DESC LIMIT 20""",
            (since_iso,),
        )
    lines.append(f"## Live Host Changes ({len(hist_rows)})")
    if hist_rows:
        for r in hist_rows:
            lines.append(f"- `[{r['event_type'].upper()}]` {r['url']}")
    else:
        lines.append("_None_")
    lines.append("")

    # ── Takeover candidates ────────────────────────────────────────────────────
    if target_id:
        takeover_rows = await db.fetchall(
            "SELECT subdomain, fingerprint FROM takeover_candidates WHERE target_id = ? AND found_at >= ? LIMIT 10",
            (target_id, since_iso),
        )
    else:
        takeover_rows = await db.fetchall(
            "SELECT subdomain, fingerprint FROM takeover_candidates WHERE found_at >= ? LIMIT 10",
            (since_iso,),
        )
    lines.append(f"## Takeover Candidates ({len(takeover_rows)})")
    if takeover_rows:
        for r in takeover_rows:
            lines.append(f"- `{r['subdomain']}` — {r['fingerprint']}")
    else:
        lines.append("_None_")
    lines.append("")

    lines.append("---")
    lines.append(f"_Generated by RECON_APP at {_now_utc().strftime('%Y-%m-%d %H:%M UTC')}_")

    return "\n".join(lines)


async def dispatch_scheduled_reports(db) -> int:
    """
    Called from scheduler tick loop once per minute.
    Returns count of reports dispatched.
    """
    from engine.api.webhooks import dispatch_webhooks

    try:
        rows = await db.fetchall(
            "SELECT * FROM report_schedules WHERE enabled = 1", ()
        )
    except Exception as exc:
        log.warning("Could not load report schedules: %s", exc)
        return 0

    sent = 0
    for row in rows:
        try:
            if not await _is_schedule_due(row):
                continue

            # Determine since_iso: last_sent_at or 24h/7d ago
            now = _now_utc()
            if row["last_sent_at"]:
                since_iso = row["last_sent_at"]
            elif row["frequency"] == "weekly":
                from datetime import timedelta
                since_iso = (now - timedelta(days=7)).isoformat()
            else:
                from datetime import timedelta
                since_iso = (now - timedelta(days=1)).isoformat()

            target_id = row["target_id"]
            domain: str | None = None
            if target_id:
                t_row = await db.fetchone(
                    "SELECT domain FROM targets WHERE id = ?", (target_id,)
                )
                domain = t_row["domain"] if t_row else target_id

            report_md = await generate_report(db, target_id, since_iso, domain)

            title = f"Recon Report — {domain or 'All Targets'}"
            channel_id = row["channel_id"]

            if channel_id:
                # Send to specific channel
                ch_row = await db.fetchone(
                    "SELECT * FROM notification_channels WHERE id = ? AND enabled = 1",
                    (channel_id,),
                )
                if ch_row:
                    import asyncio
                    import json
                    from engine.api.webhooks import _build_payload, _post_webhook
                    payload = _build_payload(ch_row["type"], "scan_complete", title, report_md[:500], {})
                    asyncio.create_task(_post_webhook(ch_row["url"], payload))
            else:
                # Broadcast to all enabled channels
                await dispatch_webhooks(db, "scan_complete", title, report_md[:500], {})

            # Update last_sent_at
            await db.execute(
                "UPDATE report_schedules SET last_sent_at = ? WHERE id = ?",
                (now.isoformat(), row["id"]),
            )
            await db.commit()
            sent += 1
            log.info("Dispatched scheduled report: %s (id=%s)", row["name"], row["id"][:8])

        except Exception as exc:
            log.error("Error dispatching report schedule %s: %s", row["id"][:8], exc)

    return sent
